In [2]:
from operator import matmul
from xml.etree import ElementInclude
import pandas as pd
import numpy as np
from mass_charge_dict import ELEMENTS2Z, Z2ELEMENTS,elements_dict
from scipy import linalg
from math import log10 , floor
import os
import shutil
from functions import *

In [19]:
molecule = 'Ethane_o'
input_path_coord = f'tests/{molecule}/coord.xyz'
input_path_hess = f'tests/{molecule}/hessian'
input_path_dipm = f'tests/{molecule}/xyz_dipm.csv'

coord,head = import_coord(input_path_coord)
hessian = import_hess(input_path_hess,coord)
dipm = import_dipm(input_path_dipm)

A = 0
for B in range(8):

    hess = hessian[3*A:3*A+3,3*B:3*B+3]

    lamb , Q = linalg.eigh(hess)

    u,w,v = linalg.svd(hess)

    print(w)

[1.29610621 1.29566102 0.47680273]
[0.25449053 0.04928211 0.04926497]
[0.04652109 0.01133094 0.00759992]
[0.0465277  0.01128833 0.00755821]
[0.04652773 0.01128831 0.0075582 ]
[1.01200073 0.06287009 0.04752877]
[1.01265975 0.062974   0.04764813]
[1.01265977 0.06297401 0.04764812]


In [22]:
import glob as glob

molecule = 'Ethane_o'
input_path = f'tests/{molecule}/'
input_path_coord = f'tests/{molecule}/coord.xyz'
input_path_hess = f'tests/{molecule}/hessian'
input_path_dipm = f'tests/{molecule}/xyz_dipm.csv'

coord,head = import_coord(input_path_coord)
hessian = import_hess(input_path_hess,coord)
dipm = import_dipm(input_path_dipm)

atoms = glob.glob(input_path_coord)

a = len(coord)
b = len(coord)
for A in range(a):
    for B in range(b):
        if A < B :
            hess = hessian[3*A:3*A+3,3*B:3*B+3]

            lamb , Q = linalg.eigh(hess)

            u,w,v = linalg.svd(hess)

            print(f'{A,B},w:{w}')


(0, 1),w:[0.25449053 0.04928211 0.04926497]
(0, 2),w:[0.04652109 0.01133094 0.00759992]
(0, 3),w:[0.0465277  0.01128833 0.00755821]
(0, 4),w:[0.04652773 0.01128831 0.0075582 ]
(0, 5),w:[1.01200073 0.06287009 0.04752877]
(0, 6),w:[1.01265975 0.062974   0.04764813]
(0, 7),w:[1.01265977 0.06297401 0.04764812]
(1, 2),w:[1.01200073 0.06287009 0.04752879]
(1, 3),w:[1.01265979 0.06297403 0.04764812]
(1, 4),w:[1.01265977 0.06297402 0.04764814]
(1, 5),w:[0.04652109 0.01133096 0.00759992]
(1, 6),w:[0.04652776 0.01128832 0.00755819]
(1, 7),w:[0.04652773 0.01128833 0.00755819]
(2, 3),w:[0.04766556 0.00056035 0.00013244]
(2, 4),w:[0.04766556 0.00056035 0.00013243]
(2, 5),w:[0.02393792 0.02070213 0.00421227]
(2, 6),w:[0.02713983 0.0188626  0.00016139]
(2, 7),w:[0.02713983 0.01886259 0.00016139]
(3, 4),w:[0.04773946 0.00056888 0.00013258]
(3, 5),w:[0.02713983 0.01886259 0.00016139]
(3, 6),w:[0.02396337 0.02073598 0.00423865]
(3, 7),w:[0.02716501 0.01886764 0.00017776]
(4, 5),w:[0.02713983 0.0188626  

In [ ]:
import glob as glob

molecule = 'Ethane_o'
input_path = f'tests/{molecule}/'
input_path_coord = f'tests/{molecule}/coord.xyz'
input_path_hess = f'tests/{molecule}/hessian'
input_path_dipm = f'tests/{molecule}/xyz_dipm.csv'

coord,head = import_coord(input_path_coord)
hessian = import_hess(input_path_hess,coord)
dipm = import_dipm(input_path_dipm)

atoms = glob.glob(input_path_coord)

a = len(coord)
b = len(coord)
for A in range(a):
    for B in range(b):
        if A < B :
            hess = hessian[3*A:3*A+3,3*B:3*B+3]

            lamb , Q = linalg.eigh(hess)

            u,w,v = linalg.svd(hess)

            print(f'{A,B},w:{w}')


In [14]:
import glob as glob

atom = glob.glob('tests/Ethane/eth/apf_coord/atoms*')
i = 1
input_path = atom[i]
input_path_coord = f'{atom[i]}/coord.xyz'
input_path_hess = f'{atom[i]}/hessian'
input_path_dipm = f'{atom[i]}/xyz_dipm.csv'

coord,head = import_coord(input_path_coord)
hessian = import_hess(input_path_hess,coord)
dipm = import_dipm(input_path_dipm)

atoms = glob.glob(input_path_coord)
print(atom[i])
#A , B = np.genfromtxt(f'{atom[i]}/atoms.txt').astype('int')
A = 0
B = 1
hess = hessian[3*A:3*A+3,3*B:3*B+3]

lamb , Q = linalg.eigh(hess)

u,w,v = linalg.svd(hess)

print(f'{A,B},w:{w}')
print(u)
print(v)

tests/Ethane/eth/apf_coord\atoms_0_1CC
(0, 1),w:[0.25449053 0.04928211 0.04926497]
[[ 3.48908153e-06  5.79129671e-06 -1.00000000e+00]
 [-1.30202640e-05  1.00000000e+00  5.79125128e-06]
 [ 1.00000000e+00  1.30202438e-05  3.48915694e-06]]
[[-3.49006912e-06 -1.65103743e-05 -1.00000000e+00]
 [-5.73062670e-06 -1.00000000e+00  1.65103943e-05]
 [ 1.00000000e+00 -5.73068432e-06 -3.48997451e-06]]
